sudo: required

services:
  - docker

script:
  - docker build . -t $DOCKER_USERNAME/dockertests_dockerfile_ansible
  - docker images

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/dockertests_dockerfile_ansible;
