- name: Enable epel repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages }}"

- name: Deploy app
  copy:
    dest: /usr/share/nginx/html/
    src: index.html
